//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_v0.dbFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTableMain()
        {
            this.TimeSpanStatic = new HashSet<TimeSpanStatic>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idSubject { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idTeacher { get; set; }
        public string Cabinet { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<bool> StatusSubject { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSpanStatic> TimeSpanStatic { get; set; }
    }
}
