//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timetable_v0.dbFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSpanStatic
    {
        public int Id { get; set; }
        public Nullable<int> IdTimeTableMain { get; set; }
        public Nullable<int> IdSubject { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idTeacher { get; set; }
        public string Cabinet { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> idGroup { get; set; }
    
        public virtual TimeTableMain TimeTableMain { get; set; }
    }
}
